### ISSUE TITLE
Dynamic resizing of cheroot Threadpool 

### ISSUE THREAD

**Issue by ppipada** [cherrypy/cheroot#190]
I'm submitting a ...
- [ ] 🐞 bug report
- [X] 🐣 feature request
- [ ] ❓ question about the decisions made in the repository

Currently the Threadpool implementation in cheroot provides a grow and shrink method which does not seem to be called anywhere inside cheroot by default. this also means that the "max" value passed in ThreadPool init is not used.
This results in a static number of threads being spawned at init time with no dynamism in response to number of requests handled by the server. As a defensive measure we generally have to init a sufficiently large number of threads (with an appopriate request_queue_size configuration). 

🐣 **Describe the solution you'd like**
ThreadPool should handle the the min and max num threads values. 
The grow and shrink decisions can be taken at request start time or can be done as a busy loop. Given that cheroot is a excellent production ready, pure python WSGI server, dynamic load handling should come baked in to it rather than an external package.   

📋 **Describe alternatives you've considered**
There is a cherrypy plugin that seems to be written explicitly for doing this: https://pypi.org/project/cherrypy-dynpool/
- This assumes cherrypy usage and does not consider Cheroot as standalone WSGI server. I would like to use cheroot as a WSGI server independent of what WSGI APP it serves (E.g: Cheroot + Flask) 
- This is an external plugin (relying on one more package "dynpool") for building dynamism into a WSGI Server. 

📋 **Additional context**
Cherrypy has a open issue that mentions this as a root cause:
https://github.com/cherrypy/cherrypy/issues/1120

**Comment by webknjaz** [comment]
Hi, I think we're not opposed to this but somebody has to write the code and submit a PR. You are welcome to do so :)

**Comment by webknjaz** [comment]
This may be related to the refactoring @the-allanc is doing now.

**Comment by the-allanc** [comment]
> This may be related to the refactoring @the-allanc is doing now.

It's not really. I think the question is whether we bring in cherrypy_dynpool into the cheroot codebase.

**Comment by webknjaz** [comment]
@the-allanc what I meant is that your change with having a manager entity should make it may easier..

**Comment by dtantsur** [comment]
Hi! I'd like to revive this since it seems to be a serious problem for scalability (you're either limited to a small number of threads or have to run a large number of threads even when nothing is happening).

Which approach would you find acceptable @webknjaz? My quick idea is to update the ThreadPool's `put` and add three new variables:
- `grow_threshold` - the proportion of threads that are busy (i.e. not `idle`), above which `put` will call `grow` before adding to the queue.
- `shrink_threshold` - the proportion of threads that are busy, below which `put` will call `shrink` before removing from the queue.
- `default_amount` - the amount of threads to pass to `shrink` or `grow`.

In other words, the implementation of `put` will try to keep the proportion of busy threads between `shrink_threshold` and `grow_threshold`.

As to the default values of these variables, I would suggest `grow_threshold` of 0.8, `shrink_threshold` of 0.4 and `default_amount` of  1. With the default `min` of 10, the first growth will happen once the number of busy threads reaches 8. If after that the number of threads gets to 4 (~ 11*0.4), the number will get back to 10.

The proposal does have a few caveats:
- The math does not make sense for `min` < 5 because the number of threads can start oscillating. The logic should either be disabled for smaller number of threads or 5 should be made the required minimum.
- The default `max` of -1 allows the threads to grow infinitely. I would recommend adding a non-infinite default value, even if it's as large as 100 or even larger.
- Usual growth algorithm double the capacity instead of adding 1 to accommodate for large spikes. I'm not sure if it's a wise idea for such heavy resources as threads.
- Will we need a local lock in `put`? I guess the logic will still work without locking, although some races will be possible

Thoughts?
