### ISSUE TITLE
[Task] Add encrypted password to Appveyor config

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cheroot#40]
@jaraco I'm implementing support for [PEP 513](https://www.python.org/dev/peps/pep-0513/) and want to have win32 tagged wheel built as well. Since I don't have maintainer access to PYPI, I'm asking you to do the following:

1. Please use [this tool](https://ci.appveyor.com/tools/encrypt) to encrypt your PYPI password.
2. After that put it into [Appveyor config](https://github.com/cherrypy/cheroot/blob/8593dc2/appveyor.yml#L9) or post in here and I'll do the rest.

Ref: 8593dc2

**Comment by jaraco** [comment]
I don't understand. CherryPy and Cheroot are pure Python libraries (as well as its dependencies). I would consider it a major blocker to drop universal platform independence.

Has cheroot added extensions that require PEP 513? Why not just keep the single universal wheel?

**Comment by jaraco** [comment]
We don't need to be creating platform-specific wheels. One of the key features of Python and CherryPy is its ability to deploy a single codebase across multiple platforms, saving the need for divergent deployment techniques such as that proposed here. Let's rely on the elegant simplicity of a universal wheel.

**Comment by webknjaz** [comment]
Well, I was thinking of taking advantage of cython. I would not prevent users from using source distribution, but rather enable speedup out of the box. It would be same `pip install` command for end-user.

**Comment by jaraco** [comment]
Aah, well that's an interesting use-case. 

I still think it's important to keep the ability for CherryPy and thus Cheroot to run natively on Python without extensions or a compiler. I would be (enthusiastically) in support of an optional "extra" dependency which provides speedups, such that if one installs CherryPy, they get the slow version, but if they install `CherryPy[speedups]` or `Cheroot[speedups]` or simply install `cheroot_speedups` (or similar), and additional package with the cython speedups will be installed and Cheroot will use that optional functionality if present.

Some projects provide this fallback behavior within a single package, but this approach leads to issues where the same package gets built differently depending on the user's environment. And while it's helpful to create binary distributions (eggs, wheels) to facilitate the installation of these binary distributions, the approach is messy and could be more cleanly handled by moving these speedups to another project/package.

And for CherryPy in particular, it's a deal breaker to add this complexity to the default installation.

Please (as you wish) explore creating a new project that contains these speedups. And since it's a new project, you can use your PyPI credentials to configure the mechanized deployment with platform-specific wheels. If you find that this approach is somehow inelegant (or worse, infeasible), let me know what impediments you encountered. I'd be happy to support this effort.

**Comment by webknjaz** [comment]
> I still think it's important to keep the ability for CherryPy and thus Cheroot to run natively on Python without extensions or a compiler.

Actually what I suggest would keep "the old way" as is. Inspired by the approach @asvetlov applied to [aiohttp](/aio-libs/aiohttp/). It's basically:
```python
try:
    setup(**args_requiring_compilation)
except BuildError:
    setup(**normal_args)
```

Currently I don't suggest adding new cython-specific code, but rather compiling existing one, and it is expected to add ~30% speedup.
