### ISSUE TITLE
LGTM bot is deprecated

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cheroot#566]
In a recent PR, I noticed that LGTM bot is deprecated and will stop working in December. Someone needs to tear that down or replace it with the Github equivalent.

**Comment by jaraco** [comment]
I think #563 is the replacement.

**Comment by webknjaz** [comment]
Yep, that's their suggested replacement but it doesn't seem a drop-in substitution, unfortunately. For example, LGTM's native comments and configs don't seem to be taken into account. Also, that PR, being autogenerated, doesn't seem to match the jsonschema's expectations, which is why the linting job fails there too.

**Comment by webknjaz** [comment]
Resolved by 1741bd8.
